### ISSUE TITLE
quest - every time I finish a custom match it crashes

### ISSUE THREAD

**Issue by ghost** [BeatTogether/BeatTogether#5] opened 2021-01-18 19:15 UTC
Every time I play a custom song with my friend (he is on pc) my game crashes

**Comment by Kevman95** [comment] 2021-01-18 19:29
Is this after playing a song? Disable Scoresaber. That is the cause of the crash.

As the crash isn't in relation to BeatTogether, I'm closing the issue.

**Closed as completed by Kevman95** 2021-01-18 19:29 UTC
